### ISSUE TITLE
init script for nodemanager fails on 12212

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#404]
Hello sir,

So I am building a WL 12.2.1.2 box (using v1.0.57 of orawls), and the /etc/init.d/nodemanager script is failing (in RHEL6).

```
# /etc/init.d/nodemanager start
Starting nodemanager:
[root@densbb3utajk99 ~]# CLASSPATH=/opt/java/jdk1.8.0_72/lib/tools.jar:/app/oracle/wls12212/wlserver/server/lib/weblogic.jar:/app/oracle/wls12212/wlserver/../oracle_common/modules/net.sf.antcontrib_1.1.0.0_1-0b3/lib/ant-contrib.jar:/app/oracle/wls12212/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/app/oracle/wls12212/wlserver/..
+ /opt/java/jdk1.8.0_72/bin/java -server -Xms32m -Xmx200m -Dweblogic.RootDirectory=/app/oracle/wls12212/wlserver/../oracle_common/common/nodemanager -Dcoherence.home=/app/oracle/wls12212/wlserver/../coherence -Dbea.home=/app/oracle/wls12212/wlserver/.. -Dweblogic.ssl.JSSEEnabled=true -Dweblogic.security.SSL.enableJSSE=true -Dweblogic.security.TrustKeyStore=CustomTrust -Dweblogic.security.CustomTrustKeyStoreFileName=/opt/java/latest/jre/lib/security/cacerts -Dweblogic.security.CustomTrustKeystorePassPhrase=changeit -Xverify:none -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/app/oracle/wls12212/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/opt/java/jdk1.8.0_72 weblogic.NodeManager -v
<Feb 2, 2017 8:02:32 AM EST> <INFO> <Loading domains file: /app/oracle/wls12212/oracle_common/common/nodemanager/nodemanager.domains>
<Feb 2, 2017 8:02:32 AM EST> <WARNING> <Domains file not found: /app/oracle/wls12212/oracle_common/common/nodemanager/nodemanager.domains>
<Feb 2, 2017 8:02:32 AM EST> <INFO> <Loading identity key store: FileName=/app/oracle/wls12212/oracle_common/common/nodemanager/security/DemoIdentity.jks, Type=jks, PassPhraseUsed=true>
<Feb 2, 2017 8:02:32 AM EST> <SEVERE> <Fatal error in NodeManager server>
weblogic.nodemanager.common.ConfigException: Identity key store file not found: /app/oracle/wls12212/oracle_common/common/nodemanager/security/DemoIdentity.jks
	at weblogic.nodemanager.server.SSLConfig.loadKeyStoreConfig(SSLConfig.java:225)
	at weblogic.nodemanager.server.SSLConfig.access$000(SSLConfig.java:33)
	at weblogic.nodemanager.server.SSLConfig$1.run(SSLConfig.java:118)
	at java.security.AccessController.doPrivileged(Native Method)
	at weblogic.nodemanager.server.SSLConfig.<init>(SSLConfig.java:115)
	at weblogic.nodemanager.server.NMServer.<init>(NMServer.java:143)
	at weblogic.nodemanager.server.NMServer.main(NMServer.java:527)
	at weblogic.NodeManager.main(NodeManager.java:31)
```

So, it is trying to load the DemoIdentity keystore, but we are using our own. I noticed in older versions of WL (like 12.1.3), there was an init script dropped at /etc/init.d/nodemanager_<domain name> which worked. So, we are sharing the same code for WL 12.2.1.2, but the init script isn't working there, and it doesn't generate the <domain name> specific init script. 

We set custom_trust to true all over, and we have our own trust_keystore_file etc.

**Comment by biemond** [comment]
Hi,

is this orautils or orawls

Can you show me the nodemanager.properties also does it work when you start it with puppet.

Thanks

**Comment by adamjk-dev** [comment]
I think it is orawls, the scripts in /opt/scripts/wls (from orautils) seem to work fine. And yes, Puppet brings things up fine, just not the init script it seems in my case.

nodemanager.properties file:
```
 cat /projects/ADAMTEST/nodemanager/nodemanager.properties
#Thu Feb 02 08:51:10 EST 2017
#Node manager properties
DomainsFile=/projects/ADAMTEST/nodemanager/nodemanager.domains
LogLimit=0
PropertiesVersion=12.2.1.2.0
AuthenticationEnabled=true
NodeManagerHome=/projects/ADAMTEST/nodemanager
JavaHome=/opt/java/latest
LogLevel=INFO
DomainsFileEnabled=true
StartScriptName=startWebLogic.sh
ListenAddress=10.239.150.230
NativeVersionEnabled=true
ListenPort=5556
LogToStderr=true
SecureListener=true
LogCount=1
StopScriptEnabled=true
QuitEnabled=false
LogAppend=true
StateCheckInterval=500
CrashRecoveryEnabled=true
StartScriptEnabled=true
LogFile=/logs/ADAMTEST/weblogic/nodemanager.log
LogFormatter=weblogic.nodemanager.server.LogFormatter
ListenBacklog=50

KeyStores=CustomIdentityAndCustomTrust
CustomIdentityKeyStoreFileName=/opt/java/latest/jre/lib/security/cacerts
CustomIdentityKeyStorePassPhrase={AES<BLAH>
CustomIdentityAlias=<BLAH wildcard>
CustomIdentityPrivateKeyPassPhrase={AES}<BLAH>
```

**Comment by biemond** [comment]
can you add the init script, basically this should do the same as your normal start nodemanager script

**Comment by adamjk-dev** [comment]
/etc/init.d/nodemanager script:

```
# cat /etc/init.d/nodemanager
#!/bin/sh
#
# nodemgr Oracle Weblogic NodeManager service
#
# chkconfig:   345 99 15
# description: Oracle Weblogic NodeManager service
#
### BEGIN INIT INFO

# Provides: nodemgr_ADAMTEST nodemanager_ADAMTEST

# Required-Start: $network $local_fs $remote_fs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Oracle Weblogic NodeManager service.
# Description: Starts and stops Oracle Weblogic NodeManager.
### END INIT INFO


# Source function library.
if test -f /lib/lsb/init-functions; then
    . /lib/lsb/init-functions
fi


. /etc/init.d/functions


# set NodeManager environment
NodeManagerLockFile=/app/oracle/wls12212/wlserver/common/nodemanager/nodemanager.log.lck


exec=/app/oracle/wls12212/wlserver/server/bin/startNodeManager.sh
prog='nodemanager'
user='ser_dvapp'


JSEE_OPTIONS="-Dweblogic.ssl.JSSEEnabled=true -Dweblogic.security.SSL.enableJSSE=true"


TRUST_OPTIONS='-Dweblogic.security.TrustKeyStore=CustomTrust -Dweblogic.security.CustomTrustKeyStoreFileName=/opt/java/latest/jre/lib/security/cacerts -Dweblogic.security.CustomTrustKeystorePassPhrase=changeit'

is_nodemgr_running() {
    local nodemgr_cnt=`ps -ef        | \
        grep -i 'java '                  | \
        grep -i ' weblogic.NodeManager '  | \
        grep -v grep                  | \
        wc -l`
    echo $nodemgr_cnt
}

get_nodemgr_pid() {
    nodemgr_pid=0
    if [ `is_nodemgr_running` -eq 1 ]; then
        nodemgr_pid=`ps -ef             | \
            grep -i 'java '                 | \
            grep -i ' weblogic.NodeManager ' | \
            grep -v grep                 | \
            tr -s ' '                    | \
            cut -d' ' -f2`
    fi
    echo $nodemgr_pid
}

check_nodemgr_status () {
    local retval=0
    local nodemgr_cnt=`is_nodemgr_running`
    if [ $nodemgr_cnt -eq 0 ]; then
        if [ -f $NodeManagerLockFile ]; then
            retval=2
        else
            retval=3
        fi
    elif [ $nodemgr_cnt -gt 1 ]; then
        retval=4
    else
        retval=0
    fi

    echo $retval
}

start() {
    ulimit -n 65535
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    sleep 10
    su - $user -c "export JAVA_OPTIONS='${JSEE_OPTIONS} ${TRUST_OPTIONS}';$exec &"
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    kill -s 9 `get_nodemgr_pid` &> /dev/null
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $NodeManagerLockFile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    local retval=`check_nodemgr_status`
    if [ $retval -eq 0 ]; then
        echo "$prog (pid:`get_nodemgr_pid`) is running..."
    elif [ $retval -eq 4 ]; then
        echo "Multiple instances of $prog are running..."
    else
        echo "$prog is stopped"
    fi
    return $retval
}

rh_status_q() {
    rh_status >/dev/null  2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo -n "Usage: $0 {"
        echo -n "start|"
        echo -n "stop|"
        echo -n "status|"
        echo -n "restart|"
        echo -n "condrestart|"
        echo -n "try-restart|"
        echo -n "reload|"
        echo -n "force-reload"
        echo "}"

        exit 2
esac
exit $?
```

**Comment by biemond** [comment]
this /app/oracle/wls12212 is your mdw home and not your domain home, from 12c you should use domain nodemanager instead 1 mdw home one

exec=/app/oracle/wls12212/wlserver/server/bin/startNodeManager.sh
prog='nodemanager'
user='ser_dvapp'

**Comment by adamjk-dev** [comment]
Which resource does that funnel in from? I couldn't track which resource laid down the init script.

**Comment by biemond** [comment]
https://github.com/biemond/biemond-orautils/blob/master/manifests/nodemanagerautostart.pp#L18

**Comment by adamjk-dev** [comment]
Yeah, if I modify my init scrip to have:

```
exec=/projects/ADAMTEST/bin/startNodeManager.sh
```

My autostart resource:
```
# Create the autostart stuff for WL
  orautils::nodemanagerautostart { 'autostart_weblogic':
    version                   => $wl_version,
    wl_home                   => $weblogic_home_dir,
    user                      => $wls_os_user,
    domain                    => $domain_name,
    domain_path               => "${domains_path}/${domain_name}",
    log_dir                   => undef,
    jsse_enabled              => true,
    custom_trust              => true,
    trust_keystore_file       => '/opt/java/latest/jre/lib/security/cacerts',
    trust_keystore_passphrase => 'changeit',
  }
```

You are saying to change the 'wl_home' variable?

**Comment by biemond** [comment]
set the domain and right version, that should do it

**Comment by adamjk-dev** [comment]
It is the 'domain' param to that resource? I didn't see where the init.d script was being created from a template etc.

**Comment by adamjk-dev** [comment]
But, I don't think what you have allows us to set it:

https://github.com/biemond/biemond-orautils/blob/master/templates/nodemanager.erb#L42
(reads from nodeMgrBinPath)

https://github.com/biemond/biemond-orautils/blob/master/manifests/nodemanagerautostart.pp#L43
(for 12.2.x, adds wl_home/server/bin)

But, my path needed to be:  /projects/ADAMTEST/bin/startNodeManager.sh

**Comment by biemond** [comment]
use version 1212, 1213 .
I see 1221 is not yet supported

**Comment by adamjk-dev** [comment]
We thinking the fix is to just amend this case statement to also include 122x?

https://github.com/biemond/biemond-orautils/blob/master/manifests/nodemanagerautostart.pp#L30

**Comment by adamjk-dev** [comment]
And I apologize, this is an issue with orautils. My mistake.
