### ISSUE TITLE
SEVERE: Error: runCmd() failed.

### ISSUE THREAD

**Issue by jmbelvar81** [biemond/biemond-orawls#503]
I´ve found that after the RCU I can´t connect to domain when the method orawls::domain is called. The error that I obtain is: - This only happend to me under Oracle Linux 6.x

/Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Orawls::Utils::Rcu[RCU_12c BBSS]/Wls_rcu[OSB12BBSS_RCU_12c_BBSS]/ensure: defined 'ensure' as 'present'
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Initializing WebLogic Scripting Tool (WL ST) ...
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Welcome to WebLogic Server Administration Scripting Shell
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Type help() for help on available comman ds
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Nov 15, 2017 1:31:57 PM com.oracle.cie.domain.script.jython.CommandExceptionHandler handleException
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: SEVERE: Error: runCmd() failed.
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: com.oracle.cie.domain.script.jython.WLST  Exception: Error reading domain:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: The domain directory must exist and contain config/config.xml
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2360)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:676)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at java.lang.reflect.Method.invoke(Method.java:497)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyReflectedFunction.__call__(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyMethod.__call__( Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyObject.__call__(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyInstance.invoke(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.pycode._pyx5.command$1(/tmp/WLSTOfflineIni7911814751668394944.py:19)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni7911814751668394944.py)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyTableCode.call(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyTableCode.call(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyTableCode.call(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyFunction.__call__(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.pycode._pyx5.readDomain$28(/tmp/WLSTOfflineIni7911814751668394944.py:127)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni7911814751668394944.py)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyTableCode.call(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyTableCode.call(U nknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyFunction.__call_ _(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.pycode._pyx140.f$0(/tmp   /download_wls/BBSS/domain_extension_BBSS.py:43)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.pycode._pyx140.call_fun ction(/tmp/download_wls/BBSS/domain_extension_BBSS.py)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyTableCode.call(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.PyCode.call(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.core.Py.runCode(Unknown   Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at org.python.util.PythonInterpreter.                       execfile(Unknown Source)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at weblogic.management.scripting.WLST                       .main(WLST.java:181)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorIm                       pl.invoke0(Native Method)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorIm                       pl.invoke(NativeMethodAccessorImpl.java:62)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.DelegatingMethodAccess                       orImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at java.lang.reflect.Method.invoke(Me                       thod.java:497)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at weblogic.WLST.main(WLST.java:47)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Caused by: com.oracle.cie.domain.script.                       ScriptException: Error reading domain:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: The domain directory must exist and cont                       ain config/config.xml
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLSTState.processCommand(WLSTState.java:233)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLScriptContext.runCmd(WLScriptContext.java:670)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    ... 31 more
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Caused by: com.oracle.cie.domain.script.                       jython.WLSTException: Error reading domain:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: The domain directory must exist and cont                       ain config/config.xml
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLScriptContext.readDomain(WLScriptContext.java:952)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorIm                       pl.invoke0(Native Method)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorIm                       pl.invoke(NativeMethodAccessorImpl.java:62)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.DelegatingMethodAccess                       orImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at java.lang.reflect.Method.invoke(Me                       thod.java:497)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLSTState.processCommand(WLSTState.java:216)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    ... 32 more
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Caused by: com.oracle.cie.domain.script.                       ScriptException: The domain directory must exist and contain config/config.xml
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.Scrip                       tExecutor.readTemplate(ScriptExecutor.java:1099)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLScriptContext.readDomain(WLScriptContext.java:943)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    ... 37 more
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Error: runCmd() failed. Do dumpStack() t                       o see details.
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: Problem invoking WLST - Traceback (inner                       most last):
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:   File "/tmp/download_wls/BBSS/domain_ex                       tension_BBSS.py", line 43, in ?
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:   File "/tmp/WLSTOfflineIni7911814751668                       394944.py", line 127, in readDomain
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:   File "/tmp/WLSTOfflineIni7911814751668                       394944.py", line 19, in command
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: The domain directory must exist and cont                       ain config/config.xml
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLScriptContext.handleException(WLScriptContext.java:2360)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at com.oracle.cie.domain.script.jytho                       n.WLScriptContext.runCmd(WLScriptContext.java:676)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorIm                       pl.invoke0(Native Method)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.NativeMethodAccessorIm                       pl.invoke(NativeMethodAccessorImpl.java:62)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at sun.reflect.DelegatingMethodAccess                       orImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:    at java.lang.reflect.Method.invoke(Me                       thod.java:497)
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: com.oracle.cie.domain.script.jython.WLST                       Exception: com.oracle.cie.domain.script.jython.WLSTException: Error reading domain:
Notice: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: The domain directory must exist and cont                       ain config/config.xml
Error: /products/oraclesoa/base/osb_12.2.1/oracle_common/common/bin/wlst.sh domain_extension_BBSS.py returned 1 instead of one of [0]
Error: /Stage[main]/Profile::Orawls::Fmw::Osb_admin_server/Orawls::Domain[BBSS]/Exec[execwlst BBSS extension BBSS]/returns: change from notrun to 0 failed: /products                       /oraclesoa/base/osb_12.2.1/oracle_common/common/bin/wlst.sh domain_extension_BBSS.py returned 1 instead of one of [0]

**Comment by biemond** [comment]
Hi,

there is not a lot of information about why this happens.  what version are you using.

```
Error reading domain
The domain directory must exist and cont ain config/config.xml
```

I guess there should be some configuration error. but why does rcu want to connect to a domain. Did you run rcu before the domain. I don't see why you should run after and why it needs a domain.

thanks

**Comment by jmbelvar81** [comment]
Thank you Biemond for so fast answer. In my previous message I wanted say (apologies for my bad English) that in the define orawls::domain I found that RCU was reported as done but the next step was reporting the attached error in previous post. I´ve found that several filesystem(s) were previously defined on the machine and when the manifest was launched  I obtained the attached error. If I change to other names the bug is avoided. I think is derivated from checking as this: 

   # create domain - If the path exist is not created the domain:
    exec { "execwlst ${domain_name} ${title}":
      command     => "${wlstPath}/wlst.sh domain_${domain_name}.py",
      environment => ["JAVA_HOME=${jdk_home_dir}"],
      unless      => "/usr/bin/test -e ${domain_dir}",
      creates     => $domain_dir,
      cwd         => $download_dir,
      require     => [File["domain.py ${domain_name} ${title}"],
                      File["${download_dir}/utils.py"],
                      File[$domains_dir],],
      timeout     => 0,
      path        => $exec_path,
      user        => $os_user,
      group       => $os_group,
    }

**Comment by biemond** [comment]
Hi, 

What happens rcu and the domain are tightly connected in 12c which was not the case in 11g.
When 1 of the 2 goes wrong you need to delete both or use a new rcu prefix and domain name.
you cannot re-use rcu it and use the same prefix.

**Comment by jmbelvar81** [comment]
Thank you for the response. My apologies for so delay answer but it was impossible to me because job related things. I will try your solution. Also I was obtained sometimes a timeout error, after RCU process. Could be linked to the same reason?. Sometimes, restarting the system or trying later I can complete but other times I need rebuild the systems completely and try again. 
Thanks a lot for your help and time. Apologies inconveniences.

**Comment by jmbelvar81** [comment]
I could execute again after I "clean" all (RCU, directories and Tables in DB, etc...) but I obtained the next error:

![image](https://user-images.githubusercontent.com/28352317/35413995-777dc966-0221-11e8-8475-b1c62a7e82a1.png)

The log indicates me the product is started:
![image](https://user-images.githubusercontent.com/28352317/35414220-23e9b70a-0222-11e8-9290-a56d10d932a4.png)

 I checked some GC errors are reported in the "gclog":
![image](https://user-images.githubusercontent.com/28352317/35414244-33d91336-0222-11e8-803e-0e013d042990.png)

 And the next processes are up:

![image](https://user-images.githubusercontent.com/28352317/35414141-f2f1c228-0221-11e8-986c-124b2a99a23e.png)

The last execution in Puppet, previously to "timeout error", was the next one (but this is reported as successful as first attached error screen shows):

![image](https://user-images.githubusercontent.com/28352317/35414417-b1aaeb7c-0222-11e8-8759-ef5e7db53158.png)

It's not clear for me the reason of this reported timeout, I supose it can't connect because some component is faulty or it's not complete started but , as I said, it's not clear for me.  Which could be the reason related to this timeout? . We have configured from some time ago this parameter related to sleep time, it has relation with this timeout?¿:
![image](https://user-images.githubusercontent.com/28352317/35414880-1be5fdf0-0224-11e8-8f06-dbe0bb6b0f1f.png)

Thank you in advance for help
