### ISSUE TITLE
OHS 12.2.1.3

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#524]
Hi Ed,

I am trying to get OHS 12.2.1.3 to work with orawls. I am using the same piece of code to startup nodemanager as ohs 12.1.3 (details below).

If I startup nodemanager using puppet, subsequent puppet runs are just fine.

However, if I say restart nodemanager from the command line, the subsequent puppet runs throw the following error. 

Why does the orawls module try to startup nodemanager when its already running ? A bit odd too that this error did not manifest in earlier versions of orawls 

startNodeManager.sh: Apr 13, 2018 4:17:26 PM weblogic.nodemanager.server.NMServer main
startNodeManager.sh: SEVERE: Fatal error in NodeManager server
startNodeManager.sh: java.io.IOException: Could not obtain exclusive lock with lockFile 'XXX/nodemanager/nodemanager.process.lck'. This most likely indicates another NodeManager process is already running in this NodeManaagerHome.
startNodeManager.sh: at weblogic.nodemanager.server.NMServer.getNMFileLock(NMServer.java:254)
startNodeManager.sh: at weblogic.nodemanager.server.NMServer.<init>(NMServer.java:153)
startNodeManager.sh: at weblogic.nodemanager.server.NMServer.getInstance(NMServer.java:134)
startNodeManager.sh: at weblogic.nodemanager.server.NMServer.main(NMServer.java:589)
startNodeManager.sh: at weblogic.NodeManager.main(NodeManager.java:31)
startNodeManager.sh: + status=1
startNodeManager.sh: + set +x

orawls::nodemanager{'nodemanager12c':
  version                                 => 1213, # for 12.2.1.3 its 12213
  middleware_home_dir                     => "same_for_1213_12213",
  weblogic_home_dir                       => "same_for_1213_12213",
  wls_domains_dir                         => "same_for_1213_12213",
  jdk_home_dir                            => "same_for_1213_12213",
  nodemanager_address                     => "same_for_1213_12213",
  nodemanager_port                        => same_for_1213_12213,
  nodemanager_secure_listener             => true,
  domain_name                             => "same_for_1213_12213",
  jsse_enabled                            => true,
  extra_arguments                         => '-Dweblogic.security.SSL.minimumProtocolVersion=TLSv1.2',
  os_user                                 => "same_for_1213_12213",
  os_group                                => "same_for_1213_12213",
  log_dir                                 => "same_for_1213_12213",
  log_file                                => "same_for_1213_12213",
  download_dir                            => "same_for_1213_12213",
  log_output                              => true,
  sleep                                   => 20,
  custom_identity                         => true,
  custom_identity_keystore_filename       => "same_for_1213_12213",
  custom_identity_keystore_passphrase     => same_for_1213_12213,
  custom_identity_alias                   => "same_for_1213_12213",
  custom_identity_privatekey_passphrase   => same_for_1213_12213,
  properties                              => {},
}

**Comment by userMar2017** [comment]
With orawls version 2.0.6, I did not have this issue

**Comment by userMar2017** [comment]
It looks like the OS service was kicking in...but it kicked in only when this puppet manifest was enabled.
Continuing to test...
