### ISSUE TITLE
orawls printing notice messages even when there is no change in properties

### ISSUE THREAD

**Issue by manishabardiya** [biemond/biemond-orawls#546]
I have provided same hiera files and running puppet apply again and again without any changes in yaml files.
puppet is printing some messages which says properties changed from [] to some other value, can someone help to understand why its printing messages even when there are no change at all?

I get this in puppet logs:
```
2018-11-26 18:30:11 +0530 Puppet (notice): Compiled catalog for machine1 in environment production in 0.32 seconds
2018-11-26 18:30:35 +0530 /Stage[main]/Amd_wls_datasources::Create_wls_datasources/Wls_datasource[Domain/DataSource]/xaproperties (notice): xaproperties changed [] to 'RollbackLocalTxUponConnClose=0 RecoverOnlyOnce=0 KeepLogicalConnOpenOnRelease=0 KeepXaConnTillTxComplete=1 XaTransactionTimeout=0 XaRetryIntervalSeconds=60 XaRetryDurationSeconds=0 ResourceHealthMonitoring=1 NewXaConnForCommit=0 XaSetTransactionTimeout=1 XaEndOnlyOnce=0 NeedTxCtxOnClose=0'
2018-11-26 18:30:38 +0530 /Stage[main]/Amd_wls_datasources::Create_wls_datasources/Wls_datasource[Domain/DS]/xaproperties (notice): xaproperties changed [] to 'RollbackLocalTxUponConnClose=0 RecoverOnlyOnce=0 KeepLogicalConnOpenOnRelease=0 KeepXaConnTillTxComplete=1 XaTransactionTimeout=0 XaRetryIntervalSeconds=60 XaRetryDurationSeconds=0 ResourceHealthMonitoring=1 NewXaConnForCommit=0 XaSetTransactionTimeout=1 XaEndOnlyOnce=0 NeedTxCtxOnClose=0'
2018-11-26 18:30:49 +0530 Puppet (notice): Applied catalog in 29.47 seconds
2018-11-26 18:30:52 +0530 Puppet (notice): Compiled catalog for machine1 in environment production in 0.46 seconds
2018-11-26 18:31:16 +0530 /Stage[main]/Amd_wls_jms_config::Create_wls_jms_queues/Wls_jms_queue[Domain/JmsServer:ProcessEngineJmsQueue]/errordestination (notice): errordestination changed '' to 'ErrorQueue'
```

**Comment by biemond** [comment]
it can be it could read the xaproperties and uses [] , in that case it wants it to change it to the requested. So we need to find out why this happening. 

can you do puppet resource wls_datasource --debug --trace. and see if it shows the xaproperties.

**Comment by manishabardiya** [comment]
below is output or the command you said - puppet resource wls_datasource --debug --trace

I dont see xaproperties in this.  but if I run puppet apply with --debug, its hows xaproperties its taking form yaml.
```
=========================================

[0;36mDebug: Runtime environment: puppet_version=4.10.1, ruby_version=2.1.9, run_mode=user, default_encoding=UTF-8[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Facter: searching for custom fact "override_wls_setting_file".[0m
[0;36mDebug: Facter: searching for override_wls_setting_file.rb in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for override_wls_setting_file.rb in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for override_wls_setting_file.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for override_wls_setting_file.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: fact "facterversion" has resolved to "3.6.4".[0m
[0;36mDebug: Facter: fact "aio_agent_version" has resolved to "1.10.1".[0m
[0;36mDebug: Facter: skipping external facts for "/users/pcicrm1/.puppetlabs/opt/facter/facts.d": No such file or directory[0m
[0;36mDebug: Facter: skipping external facts for "/users/pcicrm1/.facter/facts.d": No such file or directory[0m
[0;36mDebug: Facter: no external facts were found.[0m
[0;36mDebug: Facter: loading all custom facts.[0m
[0;36mDebug: Facter: loading custom fact directories from config file[0m
[0;36mDebug: Facter: searching for custom facts in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/orawls/lib/facter/orawls.rb.[0m
[0;36mDebug: Facter: searching for custom fact "kernel".[0m
[0;36mDebug: Facter: searching for kernel.rb in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for kernel.rb in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for kernel.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for kernel.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: resolving kernel facts.[0m
[0;36mDebug: Facter: fact "kernel" has resolved to "Linux".[0m
[0;36mDebug: Facter: fact "kernelrelease" has resolved to "3.10.0-514.el7.x86_64".[0m
[0;36mDebug: Facter: fact "kernelmajversion" has resolved to "3.10".[0m
[0;36mDebug: Facter: fact "kernelversion" has resolved to "3.10.0".[0m
[0;36mDebug: Facter: searching for custom fact "override_orainst_dir".[0m
[0;36mDebug: Facter: searching for override_orainst_dir.rb in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for override_orainst_dir.rb in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for override_orainst_dir.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for override_orainst_dir.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: loading all custom facts.[0m
[0;36mDebug: Facter: loading custom fact directories from config file[0m
[0;36mDebug: Facter: searching for custom facts in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for custom facts in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/stdlib/lib/facter/facter_dot_d.rb.[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/stdlib/lib/facter/pe_version.rb.[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/stdlib/lib/facter/package_provider.rb.[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Executing: '/usr/bin/rpm --version'[0m
[0;36mDebug: Executing: '/usr/bin/rpm --version'[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Executing: '/usr/bin/rpm -ql rpm'[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Executing: '/usr/bin/rpm --version'[0m
[0;36mDebug: Failed to load library 'cfpropertylist' for feature 'cfpropertylist'[0m
[0;36mDebug: Executing: '/usr/bin/rpm --version'[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/stdlib/lib/facter/service_provider.rb.[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Facter: searching for custom fact "operatingsystem".[0m
[0;36mDebug: Facter: searching for operatingsystem.rb in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for operatingsystem.rb in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for operatingsystem.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for operatingsystem.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: resolving operating system facts.[0m
[0;36mDebug: Facter: executing command: /usr/bin/lsb_release -a[0m
[0;36mDebug: Facter: LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch[0m
[0;36mDebug: Facter: Distributor ID:	RedHatEnterpriseServer[0m
[0;36mDebug: Facter: Description:	Red Hat Enterprise Linux Server release 7.3 (Maipo)[0m
[0;36mDebug: Facter: Release:	7.3[0m
[0;36mDebug: Facter: Codename:	Maipo[0m
[0;36mDebug: Facter: process exited with status code 0.[0m
[0;36mDebug: Facter: fact "osfamily" has resolved to "RedHat".[0m
[0;36mDebug: Facter: fact "operatingsystemmajrelease" has resolved to "7".[0m
[0;36mDebug: Facter: fact "operatingsystemrelease" has resolved to "7.3".[0m
[0;36mDebug: Facter: fact "hardwaremodel" has resolved to "x86_64".[0m
[0;36mDebug: Facter: fact "architecture" has resolved to "x86_64".[0m
[0;36mDebug: Facter: fact "lsbdistid" has resolved to "RedHatEnterpriseServer".[0m
[0;36mDebug: Facter: fact "lsbdistcodename" has resolved to "Maipo".[0m
[0;36mDebug: Facter: fact "lsbdistdescription" has resolved to "Red Hat Enterprise Linux Server release 7.3 (Maipo)".[0m
[0;36mDebug: Facter: fact "lsbmajdistrelease" has resolved to "7".[0m
[0;36mDebug: Facter: fact "lsbminordistrelease" has resolved to "3".[0m
[0;36mDebug: Facter: fact "lsbdistrelease" has resolved to "7.3".[0m
[0;36mDebug: Facter: fact "lsbrelease" has resolved to ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch".[0m
[0;36mDebug: Facter: fact "operatingsystem" has resolved to "RedHat".[0m
[0;36mDebug: Facter: fact "selinux" has resolved to false.[0m
[0;36mDebug: Facter: fact "os" has resolved to {
  architecture => "x86_64",
  distro => {
    codename => "Maipo",
    description => "Red Hat Enterprise Linux Server release 7.3 (Maipo)",
    id => "RedHatEnterpriseServer",
    release => {
      full => "7.3",
      major => "7",
      minor => "3"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.3",
    major => "7",
    minor => "3"
  },
  selinux => {
    enabled => false
  }
}.[0m
[0;36mDebug: Facter: searching for custom fact "osfamily".[0m
[0;36mDebug: Facter: searching for osfamily.rb in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for osfamily.rb in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for osfamily.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for osfamily.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: searching for custom fact "operatingsystemrelease".[0m
[0;36mDebug: Facter: searching for operatingsystemrelease.rb in /opt/puppetlabs/puppet/modules/orawls/lib/facter.[0m
[0;36mDebug: Facter: searching for operatingsystemrelease.rb in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for operatingsystemrelease.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for operatingsystemrelease.rb in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/stdlib/lib/facter/puppet_settings.rb.[0m
[0;32mInfo: Facter: loading custom facts from /opt/puppetlabs/puppet/modules/stdlib/lib/facter/root_home.rb.[0m
[0;36mDebug: Facter: searching for custom facts in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for custom facts in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: custom fact "override_orainst_dir" was not found.[0m
[0;36mDebug: ora_inventory_path is default to /etc[0m
[0;36mDebug: Facter: custom fact "override_orainst_dir" was not found.[0m
[0;36mDebug: ora_inventory_path is default to /etc[0m
[0;36mDebug: Facter: custom fact "override_weblogic_user" was not found.[0m
[0;36mDebug: orawls.rb weblogic user is oracle[0m
[0;36mDebug: orawls.rb oraInstPath [0m
[0;36mDebug: orawls.rb oraProducts NotFound[0m
[0;36mDebug: orawls.rb mdw11gHomes [0m
[0;36mDebug: orawls.rb mdw12cHomes [][0m
[0;36mDebug: Facter: custom fact "override_wls_domains_file" was not found.[0m
[0;36mDebug: wls_domains_file is default to /etc/wls_domains.yaml[0m
[0;36mDebug: /etc/wls_domains.yaml not found[0m
[0;36mDebug: orawls.rb ora_mdw_homes [0m
[0;36mDebug: orawls.rb ora_mdw_cnt 0[0m
[0;36mDebug: Facter: searching for custom facts in /opt/puppetlabs/puppet/modules/stdlib/lib/facter.[0m
[0;36mDebug: Facter: searching for custom facts in /users/pcicrm1/.puppetlabs/opt/puppet/cache/lib/facter.[0m
[0;36mDebug: Facter: searching for custom facts in /users/pcicrm1/.puppetlabs/opt/puppet/cache/facts.[0m
[0;36mDebug: Facter: custom fact "override_wls_setting_file" was not found.[0m
[0;36mDebug: wls_setting_file is default to /etc/wls_setting.yaml[0m
[0;36mDebug: index wls_datasource[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Evicting cache entry for environment 'production'[0m
[0;36mDebug: Caching environment 'production' (ttl = 0 sec)[0m
[0;36mDebug: Executing: wlstScript with action index[0m
[0;36mDebug: domain found default[0m
[1;31mError: Could not run: weblogic_home_dir cannot be nil, check the wls_setting resource type
/opt/external/puppet/modules/orawls/lib/utils/wls_access.rb:325:in `execute_wlst'
/opt/external/puppet/modules/orawls/lib/utils/wls_access.rb:174:in `block in wlst'
/opt/external/puppet/modules/orawls/lib/utils/wls_access.rb:172:in `each'
/opt/external/puppet/modules/orawls/lib/utils/wls_access.rb:172:in `wlst'
/opt/external/puppet/modules/orawls/lib/puppet/type/wls_datasource.rb:20:in `block (2 levels) in <module:Puppet>'
/opt/external/puppet/modules/easy_type/lib/easy_type/provider.rb:182:in `instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1170:in `block in instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1163:in `collect'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1163:in `instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/resource/ral.rb:24:in `search'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:269:in `search'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:221:in `find_or_save_resources'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:136:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:366:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:542:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'[0m
```

**Comment by biemond** [comment]
I would expect to see the wlst output on this �[0;36mDebug: index wls_datasource�[0m

can you paste your datasource entry so I can re-produce it.

**Comment by manishabardiya** [comment]
you mean this?

===========================
wls_datasources:
  '%{hiera(''domain_name'')}/DataSource':
    ensure: 'present'
    drivername: 'oracle.jdbc.xa.client.OracleXADataSource'
    jndinames:
    - 'DataSource'
    initialcapacity: '1'
    maxcapacity: '50'
    mincapacity: '1'
    statementcachesize: '10'
    testconnectionsonreserve: '0'
    fanenabled: '0'
    target: '%{hiera(''targets'')}'
    targettype: '%{hiera(''targettypes'')}'
    testtablename: 'SQL SELECT 1 FROM DUAL'
    initsql: SQL ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_NUMERIC_CHARACTERS
      = '.,'
    url: 'jdbc:oracle:thin:@machine1:1521:db'
    user: 'ab'
    password: 'ab'
    usexa: '1'
    xaproperties:
    - 'RollbackLocalTxUponConnClose=0'
    - 'RecoverOnlyOnce=0'
    - 'KeepLogicalConnOpenOnRelease=0'
    - 'KeepXaConnTillTxComplete=1'
    - 'XaTransactionTimeout=0'
    - 'XaRetryIntervalSeconds=60'
    - 'XaRetryDurationSeconds=0'
    - 'ResourceHealthMonitoring=1'
    - 'NewXaConnForCommit=0'
    - 'XaSetTransactionTimeout=1'
    - 'XaEndOnlyOnce=0'
    - 'NeedTxCtxOnClose=0'

**Comment by manishabardiya** [comment]
and jms queue entry where other message is as below:
=========================
wls_jms_queues:
      "%{hiera('domain_name')}/%{hiera('jms_module_name1')}:ProcessEngineJmsQueue":
         ensure: 'present'
         jndiname: 'ProcessEngineJmsQueue'
         defaulttargeting: "0"
         subdeployment: "%{hiera('jms_subdeployment_name1')}"
         distributed: "0"
         errordestination: 'ErrorQueue'
         redeliverydelay: '-1'
         redeliverylimit: '-1'
      "%{hiera('domain_name')}/%{hiera('jms_module_name1')}:ErrorQueue":
         ensure: 'present'
         jndiname: 'ErrorQueue'
         defaulttargeting: "0"
         subdeployment: "%{hiera('jms_subdeployment_name1')}"
         distributed: "1"
         redeliverydelay: '-1'
         redeliverylimit: '-1'

**Comment by manishabardiya** [comment]
any suggestion?

**Comment by manishabardiya** [comment]
@biemond   - any suggestions to overcome this?
